### ISSUE TITLE
installer.sh should prompt the user to append `$HOME/.local/bin` to `PATH`

### ISSUE THREAD

**Issue by grtcdr** [friciwolf/Rocket#3]
```
chmod +x rocket
mkdir -p ~/.local/bin/
cp rocket ~/.local/bin/rocket
```

A good chunk of people don't have `~/.local/bin` in their `PATH`, so running `rocket` will notify them that no such file exists on the system. So you might want to consider echoing a warning that prompts the user to add that path to the `PATH` environment variable.

**Comment by friciwolf** [comment]
I think I could add a warning to the installer script, however a better solution would be to not only notify the user, but to also add ```~/.local/bin``` to their ```PATH``` upon installation, which I think goes beyond my scripting abilities. An alternative would be to place the executable to ```/bin``` directly, but I somehow like the idea of local installations only.

**Comment by grtcdr** [comment]
I'm not sure if you are familiar with Rust and its package manager, cargo.

But upon installation, cargo notifies you to add its bin directory to your path, so you can run those programs you installed.

The gem (for Ruby) package manager also shares this trait.

Not every shell operates the same so appending it to PATH of the user's shell dotfile is what I'd consider a headache.

**Comment by friciwolf** [comment]
I'm not sure I follow but you're proposing to package the binaries as a gem (or sth. similar) just like [colorls](https://github.com/athityakumar/colorls) does?
If that solves the issue you've described, it's a solution I'd be happy with :)

**Comment by grtcdr** [comment]
No, I was simply telling you that it's perfectly fine to settle with just notifiying the user to add the path to **PATH**.

**Comment by friciwolf** [comment]
Alright I see! If you know how it's done (you seem to know more things on this area than me), could you make a pull request? Now my focus would be on different things, however your feature would definitely be helpful for new-coming users!
