### ISSUE TITLE
[Request] Gnome-like folder utility

### ISSUE THREAD

**Issue by Jing-Linux** [friciwolf/Rocket#5]
This is a fantastic app, but can you make a Gnome menu-like folder utility? It will be even better if so.

**Comment by friciwolf** [comment]
Hi @Jing-Linux I'm glad you enjoy using Rocket!
The thing is, I only had the alphabetical layout in mind as I was developing Rocket -- however, the idea to organize items in folders has also come in my mind. If you look at the source code, you can even find traces of preparations to implement such a feature.

On the other hand, Rocket perfectly covers my needs in its current state and I have moved on a bit in real life with other things. That does not necessarily mean I will never implement the feature you requested; it only means that development is slowing down. As a side-note, I'd make the implementation speed of this feature dependent on the interest in it.

I can promise you something though: once Rocket supports folders, I'll announce it both in r/unixporn and in r/kde, and it will be released under Rocket 2.0.

**Comment by Jing-Linux** [comment]
Okay, thanks for the reply! And good luck to you! I'll probably close this issue after you make such feature.

**Comment by Jing-Linux** [comment]
Great job! Now will be a good time to close this issue and consider that folder function is complete.

**Comment by friciwolf** [comment]
Thanks for following up!
There are still some minor bugs which need fixing though, this is why the issue was still open and no 2.0 release has been made. I'm currently on holiday, but I'll come back to them when it's over :)
